import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * sidebars are scaffolded as autogenerated trees rooted at each product folder.
 * structure-architect agent will replace these with hand-curated category trees
 * once content migration begins, mirroring source/_data/navigation.yml.
 */
const sidebars: SidebarsConfig = {
  dxlSidebar: [{type: 'autogenerated', dirName: 'dxl'}],
  platformSidebar: [{type: 'autogenerated', dirName: 'platform'}],
  softwareSidebar: [{type: 'autogenerated', dirName: 'software'}],
  partsSidebar: [{type: 'autogenerated', dirName: 'parts'}],
  eduSidebar: [{type: 'autogenerated', dirName: 'edu'}],
  faqSidebar: [{type: 'autogenerated', dirName: 'faq'}],
};

export default sidebars;
