import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Hand-curated sidebars mirroring source/_data/navigation.yml ordering.
 * dxlSidebar follows the original ROBOTIS e-Manual structure:
 *   DYNAMIXEL overview → Quick start → Y, P, X, MX, AX → Protocol/CRC → EX, DX, RX (legacy) → PRO
 */
const sidebars: SidebarsConfig = {
  dxlQuickStartSidebar: [
    'dxl/index',
    'dxl/dxl-quick-start-guide',
    'dxl/dxl-quick-start-insert',
  ],

  dxlSidebar: [
    {
      type: 'category',
      label: 'Y Series',
      link: {type: 'doc', id: 'dxl/y/index'},
      items: [{type: 'autogenerated', dirName: 'dxl/y'}],
    },
    {
      type: 'category',
      label: 'P Series',
      link: {type: 'doc', id: 'dxl/p/index'},
      items: [{type: 'autogenerated', dirName: 'dxl/p'}],
    },
    {
      type: 'category',
      label: 'X Series',
      link: {type: 'doc', id: 'dxl/x/x'},
      items: [
        {type: 'autogenerated', dirName: 'dxl/x'},
        'dxl/x_c',
        'dxl/x_h',
        'dxl/x_l',
        'dxl/x_m',
      ],
    },
    {
      type: 'category',
      label: 'MX Series',
      link: {type: 'doc', id: 'dxl/mx'},
      items: [{type: 'autogenerated', dirName: 'dxl/mx'}],
    },
    {
      type: 'category',
      label: 'AX Series',
      link: {type: 'doc', id: 'dxl/ax'},
      items: [{type: 'autogenerated', dirName: 'dxl/ax'}],
    },

    {
      type: 'category',
      label: 'EX Series',
      link: {type: 'doc', id: 'dxl/ex'},
      items: [{type: 'autogenerated', dirName: 'dxl/ex'}],
    },
    {
      type: 'category',
      label: 'DX Series',
      link: {type: 'doc', id: 'dxl/dx'},
      items: [{type: 'autogenerated', dirName: 'dxl/dx'}],
    },
    {
      type: 'category',
      label: 'RX Series',
      link: {type: 'doc', id: 'dxl/rx'},
      items: [{type: 'autogenerated', dirName: 'dxl/rx'}],
    },
    {
      type: 'category',
      label: 'PRO Series',
      link: {type: 'doc', id: 'dxl/pro/pro'},
      items: [
        {type: 'autogenerated', dirName: 'dxl/pro'},
        'dxl/pro_h',
        'dxl/pro_l',
        'dxl/pro_m',
      ],
    },
  ],
  protocolSidebar: [
    'dxl/protocol1',
    'dxl/protocol2',
    'dxl/crc',
  ],
  /*
   * Systems(=platform) 소분류별 사이드바.
   * Mega-menu 의 각 제품 링크는 그 제품 폴더 안의 페이지로 향하므로,
   * 폴더 단위로 autogenerated 사이드바를 두면 사용자가 페이지에 진입했을 때
   * 그 제품 전용 사이드바만 보인다. sidebars 객체 키 순서가 검색 우선순위라
   * 좁은 범위(제품 폴더) 사이드바를 platformSidebar 보다 먼저 둔다.
   */
  aiworkerSidebar: [{type: 'autogenerated', dirName: 'platform/aiworker'}],
  aisapiensSidebar: [{type: 'autogenerated', dirName: 'platform/aisapiens'}],
  opSidebar: [{type: 'autogenerated', dirName: 'platform/op'}],
  op2Sidebar: [{type: 'autogenerated', dirName: 'platform/op2'}],
  op3Sidebar: [{type: 'autogenerated', dirName: 'platform/op3'}],
  thormang3Sidebar: [{type: 'autogenerated', dirName: 'platform/thormang3'}],
  hx5d20Sidebar: [{type: 'autogenerated', dirName: 'platform/hx5_d20'}],
  rhp12rnSidebar: [{type: 'autogenerated', dirName: 'platform/rh_p12_rn'}],
  omySidebar: [{type: 'autogenerated', dirName: 'platform/omy'}],
  omxSidebar: [{type: 'autogenerated', dirName: 'platform/omx'}],
  openmanipulatorPSidebar: [{type: 'autogenerated', dirName: 'platform/openmanipulator_p'}],
  openmanipulatorXSidebar: [{type: 'autogenerated', dirName: 'platform/openmanipulator_x'}],
  manipulatorHSidebar: [{type: 'autogenerated', dirName: 'platform/manipulator_h'}],
  turtlebot3Sidebar: [{type: 'autogenerated', dirName: 'platform/turtlebot3'}],
  /* Mega-menu 에 노출되지 않는 잡탕 폴더 + 단일 페이지 */
  platformSidebar: [
    'platform/platform',
    'platform/ai_manipulator_main',
    'platform/rh_p12_rn_main',
    {type: 'autogenerated', dirName: 'platform/common'},
    {type: 'autogenerated', dirName: 'platform/msgs'},
  ],
  softwareSidebar: [{type: 'autogenerated', dirName: 'software'}],
  partsSidebar: [{type: 'autogenerated', dirName: 'parts'}],
  eduSidebar: [{type: 'autogenerated', dirName: 'edu'}],
  faqSidebar: [{type: 'autogenerated', dirName: 'faq'}],
};

export default sidebars;
