import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Hand-curated sidebars mirroring source/_data/navigation.yml ordering.
 * dxlSidebar follows the original ROBOTIS e-Manual structure:
 *   DYNAMIXEL overview → Quick start → Y, P, X, MX, AX → Protocol/CRC → EX, DX, RX (legacy) → PRO
 */
const sidebars: SidebarsConfig = {
  dxlSidebar: [
    'dxl/index',
    'dxl/dxl-quick-start-guide',

    {
      type: 'category',
      label: 'Y Series',
      link: {type: 'doc', id: 'dxl/y/index'},
      items: [{type: 'autogenerated', dirName: 'dxl/y'}],
    },
    {
      type: 'category',
      label: 'P Series',
      link: {type: 'doc', id: 'dxl/p/index'},
      items: [{type: 'autogenerated', dirName: 'dxl/p'}],
    },
    {
      type: 'category',
      label: 'X Series',
      link: {type: 'doc', id: 'dxl/x/x'},
      items: [
        {type: 'autogenerated', dirName: 'dxl/x'},
        'dxl/x_c',
        'dxl/x_h',
        'dxl/x_l',
        'dxl/x_m',
      ],
    },
    {
      type: 'category',
      label: 'MX Series',
      link: {type: 'doc', id: 'dxl/mx'},
      items: [{type: 'autogenerated', dirName: 'dxl/mx'}],
    },
    {
      type: 'category',
      label: 'AX Series',
      link: {type: 'doc', id: 'dxl/ax'},
      items: [{type: 'autogenerated', dirName: 'dxl/ax'}],
    },

    'dxl/protocol1',
    'dxl/protocol2',
    'dxl/crc',

    {
      type: 'category',
      label: 'EX Series',
      link: {type: 'doc', id: 'dxl/ex'},
      items: [{type: 'autogenerated', dirName: 'dxl/ex'}],
    },
    {
      type: 'category',
      label: 'DX Series',
      link: {type: 'doc', id: 'dxl/dx'},
      items: [{type: 'autogenerated', dirName: 'dxl/dx'}],
    },
    {
      type: 'category',
      label: 'RX Series',
      link: {type: 'doc', id: 'dxl/rx'},
      items: [{type: 'autogenerated', dirName: 'dxl/rx'}],
    },
    {
      type: 'category',
      label: 'PRO Series',
      link: {type: 'doc', id: 'dxl/pro/pro'},
      items: [
        {type: 'autogenerated', dirName: 'dxl/pro'},
        'dxl/pro_h',
        'dxl/pro_l',
        'dxl/pro_m',
      ],
    },
  ],
  platformSidebar: [{type: 'autogenerated', dirName: 'platform'}],
  softwareSidebar: [{type: 'autogenerated', dirName: 'software'}],
  partsSidebar: [{type: 'autogenerated', dirName: 'parts'}],
  eduSidebar: [{type: 'autogenerated', dirName: 'edu'}],
  faqSidebar: [{type: 'autogenerated', dirName: 'faq'}],
};

export default sidebars;
